version: "3.8"

services:
  plex-album-auto-rater:
    image: tobotec/plex-album-auto-rater:latest
    environment:
      environment:
      PLEX_URL: ${PLEX_URL}
      PLEX_TOKEN: ${PLEX_TOKEN}
      PLEX_MUSIC_LIBRARY: ${PLEX_MUSIC_LIBRARY}
      DRY_RUN: ${DRY_RUN}
      NEUTRAL_RATING: ${NEUTRAL_RATING}
      CONFIDENCE_WEIGHT: ${CONFIDENCE_WEIGHT}
      MIN_COVERAGE: ${MIN_COVERAGE}
      MIN_TRACK_DURATION: ${MIN_TRACK_DURATION}
      ROUNDING_BIAS_BAD_ALBUM: ${ROUNDING_BIAS_BAD_ALBUM}
      ROUNDING_BIAS_GOOD_ALBUM: ${ROUNDING_BIAS_GOOD_ALBUM}
      UNRATE_EMPTY_ALBUMS: ${UNRATE_EMPTY_ALBUMS}
      PYTHONUNBUFFERED: "1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=plex-album-auto-rater"
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == worker
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 3 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
